/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo.programacion.curso;

import codigo.programacion.Documentacion.Documentacion;
import codigo.programacion.Search.Search;
import codigo.programacion.admin.Admin;
import codigo.programacion.conexionDB.DB;
import codigo.programacion.home.Home;
import codigo.programacion.interfaces.Go;
import codigo.programacion.interfaces.init;
import codigo.programacion.model.Curso;
import codigo.programacion.model.User;
import codigo.programacion.utils.CursoRenderer;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author HugoLuna
 */
public class AllCourses extends javax.swing.JFrame implements Go, init {

    /*
    variables
     */
    public DefaultListModel<Curso> model;
    int counter = 0;
    int position = 0;
    public User user = null;

    /**
     * Creates new form AllCourses
     */
    public AllCourses(User user) {
        this.user = user;
        initComponents();
        initViews();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        cursoBtn = new javax.swing.JLabel();
        docBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        photoProfile = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        searchBtn = new javax.swing.JLabel();
        fieldSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        containerCursos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        button1 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel9.setMaximumSize(new java.awt.Dimension(1336, 755));
        jPanel9.setMinimumSize(new java.awt.Dimension(1165, 755));
        jPanel9.setPreferredSize(new java.awt.Dimension(1336, 755));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 18, 50));
        jPanel10.setPreferredSize(new java.awt.Dimension(70, 750));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 70, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/menu.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/home.png"))); // NOI18N
        Home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        jPanel10.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 70, 50));

        cursoBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cursoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/play-button.png"))); // NOI18N
        cursoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cursoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cursoBtnMouseClicked(evt);
            }
        });
        jPanel10.add(cursoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 70, 50));

        docBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        docBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/docs.png"))); // NOI18N
        docBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        docBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docBtnMouseClicked(evt);
            }
        });
        jPanel10.add(docBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 70, 50));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 760));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1300, 60));

        photoProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/user.png"))); // NOI18N
        photoProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        photoProfile.setMaximumSize(new java.awt.Dimension(54, 54));
        photoProfile.setMinimumSize(new java.awt.Dimension(54, 54));
        photoProfile.setPreferredSize(new java.awt.Dimension(54, 54));
        photoProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoProfileMouseClicked(evt);
            }
        });

        userName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("Usuario");
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameMouseClicked(evt);
            }
        });

        searchBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/search.png"))); // NOI18N
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        fieldSearch.setText("Buscar un curso...");
        fieldSearch.setToolTipText("");
        fieldSearch.setSize(new java.awt.Dimension(80, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Código Programación");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(photoProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userName)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldSearch)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(userName)
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(photoProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel9.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 1230, 60));

        containerCursos.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        List.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane1.setViewportView(List);

        button1.setLabel("button1");

        jButton1.setText("jButton1");

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout containerCursosLayout = new javax.swing.GroupLayout(containerCursos);
        containerCursos.setLayout(containerCursosLayout);
        containerCursosLayout.setHorizontalGroup(
            containerCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCursosLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        containerCursosLayout.setVerticalGroup(
            containerCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCursosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel9.add(containerCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 1230, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:

        goTo("Home");
    }//GEN-LAST:event_HomeMouseClicked

    private void photoProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoProfileMouseClicked
        // TODO add your handling code here:
        goTo("Perfil");
    }//GEN-LAST:event_photoProfileMouseClicked

    private void userNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameMouseClicked

    private void cursoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cursoBtnMouseClicked
        // TODO add your handling code here:
        goTo("Curso");
    }//GEN-LAST:event_cursoBtnMouseClicked

    private void docBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docBtnMouseClicked
        // TODO add your handling code here:
        goTo("Doc");
    }//GEN-LAST:event_docBtnMouseClicked

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        String text = fieldSearch.getText().toString();
        if (!text.isEmpty() && !text.equals("Buscar un curso...")) {
            
            dispose();
            Search s = new Search(user,text);
            s.setVisible(true);
            
        }
    }//GEN-LAST:event_searchBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    public javax.swing.JList<Curso> List;
    private java.awt.Button button1;
    private javax.swing.JPanel containerCursos;
    private javax.swing.JLabel cursoBtn;
    private javax.swing.JLabel docBtn;
    private javax.swing.JTextField fieldSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel photoProfile;
    private javax.swing.JLabel searchBtn;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void goTo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void goTo(String screen) {
        switch (screen) {
            case "Home":
                Home home = new Home(user);
                home.setVisible(true);
                break;
            case "Admin":
                Admin admin = new Admin(user);
                admin.setVisible(true);
                break;
            case "Cursos":

                AllCourses ac = new AllCourses(user);
                ac.setVisible(true);
                break;
            case "Doc":
                Documentacion d = new Documentacion(user);
                d.setVisible(true);
                break;
            default:
                break;
        }
    }

    @Override
    public void initViews() {
        userName.setText(user.getUsuario());
        model = new DefaultListModel<>();

        try {

            Connection bd = DB.getConection();
            Statement state = bd.createStatement();

            String consulta = "SELECT * FROM curso";
            ResultSet resultset = state.executeQuery(consulta);

            if (resultset != null) {

                while (resultset.next()) {
                    // get fields
                    String id = resultset.getString("id");
                    String nombre = resultset.getString("nombre");
                    String descripcion = resultset.getString("descripcion");
                    String autor = resultset.getString("autor");
                    String estudiantes = resultset.getString("estudiantes");
                    String img = resultset.getString("img");
                    String created_at = resultset.getString("created_at");

                    model.addElement(new Curso(id, nombre, descripcion, autor, estudiantes, img, created_at));

                }

            }
            counter = resultset.getFetchSize();
            System.out.println("cont: " + counter);

        } catch (Exception e) {
            System.err.println("Error al traer los datos para la lista");
        }
        List.setLayoutOrientation(JList.HORIZONTAL_WRAP);

        MouseListener mouseListener = new MouseAdapter() {
            public void mouseClicked(MouseEvent mouseEvent) {
                List = (JList) mouseEvent.getSource();

                if (mouseEvent.getClickCount() == 1) {
                    int index = List.locationToIndex(mouseEvent.getPoint());
                    //System.out.println(model.get(index).getNombre());
                }

                if (mouseEvent.getClickCount() == 2) {
                    int index = List.locationToIndex(mouseEvent.getPoint());
                    System.out.println(model.get(index).getNombre());
                    String id_course = model.get(index).getId();
                    dispose();

                    CursoView cv = new CursoView(user, id_course);
                    cv.setVisible(true);

                }
            }
        };
        List.addMouseListener(mouseListener);

        // create JList with model
        List.setModel(model);
        // set cell renderer
        List.setCellRenderer(new CursoRenderer());

    }
}
