/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo.programacion.curso;

import codigo.programacion.conexionDB.DB;
import codigo.programacion.home.Home;
import codigo.programacion.interfaces.Go;
import codigo.programacion.interfaces.init;
import codigo.programacion.model.Contenido;
import codigo.programacion.model.Curso;
import codigo.programacion.model.User;
import codigo.programacion.utils.CircleButton;
import codigo.programacion.utils.ContenidoRenderer;
import codigo.programacion.utils.CursoRenderer;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HugoLuna
 */
public class CursoView extends javax.swing.JFrame implements Go, init {

    /**
     * init variables
     */
    public static User user = null;
    public static String id_course;
    public static int id_contenido;
    public DefaultListModel<Contenido> model;
    public boolean validateCourse = false;

    /**
     * Creates new form Curso
     */
    public CursoView(User user, String id_course) {
        initComponents();
        this.user = user;
        this.id_course = id_course;
        System.out.println("ID Curso: " + id_course);
        validateExist();
        initViews();

    }

    public void validateExist() {
        try {
            Connection conDB = DB.getConection();
            Statement state = conDB.createStatement();

            String query = "SELECT * FROM inscrito WHERE id_usuario = '" + user.getId() + "' AND id_curso = '" + id_course + "'";

            ResultSet rs = state.executeQuery(query);

            if (!rs.first()) {
                validateCourse = true;
                actionBtn.setIcon(new ImageIcon(getClass().getResource("/imagenes/add.png")));

            } else {
                validateCourse = false;
                actionBtn.setIcon(new ImageIcon(getClass().getResource("/imagenes/play-button.png")));

            }

        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        photoProfile = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        containerCursos = new javax.swing.JPanel();
        imageCourse = new javax.swing.JLabel();
        nameCourse = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        listContentCourse = new javax.swing.JList();
        button1 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        actionBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        autor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionCurso = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 755));
        setMinimumSize(new java.awt.Dimension(1300, 755));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1300, 755));

        jPanel9.setMaximumSize(new java.awt.Dimension(1336, 755));
        jPanel9.setMinimumSize(new java.awt.Dimension(1165, 755));
        jPanel9.setPreferredSize(new java.awt.Dimension(1336, 755));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 18, 50));
        jPanel10.setPreferredSize(new java.awt.Dimension(70, 750));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 70, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/menu.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/home.png"))); // NOI18N
        Home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        jPanel10.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 70, 50));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/play-button.png"))); // NOI18N
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 70, 50));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/docs.png"))); // NOI18N
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 70, 50));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 760));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1300, 60));

        photoProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photoProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/user.png"))); // NOI18N
        photoProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        photoProfile.setMaximumSize(new java.awt.Dimension(54, 54));
        photoProfile.setMinimumSize(new java.awt.Dimension(54, 54));
        photoProfile.setPreferredSize(new java.awt.Dimension(54, 54));
        photoProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoProfileMouseClicked(evt);
            }
        });

        userName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("Usuario");
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameMouseClicked(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/codigo/programacion/home/search.png"))); // NOI18N

        jTextField1.setText("Buscar un curso...");
        jTextField1.setToolTipText("");
        jTextField1.setSize(new java.awt.Dimension(80, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Código Programación");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(photoProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userName)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(userName)
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(photoProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel9.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 1230, 60));

        containerCursos.setBackground(new java.awt.Color(21, 150, 135));

        imageCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/android.png"))); // NOI18N

        nameCourse.setFont(new java.awt.Font("Lucida Grande", 3, 36)); // NOI18N
        nameCourse.setForeground(new java.awt.Color(255, 255, 255));
        nameCourse.setText("Curso de Desarrollo Android");

        listContentCourse.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listContentCourse.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listContentCourse);

        button1.setLabel("button1");

        jButton1.setText("jButton1");

        jCheckBox1.setText("jCheckBox1");

        actionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/play-button.png"))); // NOI18N
        actionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionBtnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion del Curso");

        autor.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        autor.setForeground(new java.awt.Color(255, 255, 255));
        autor.setText("Autor: Hugo Dario Luna Cruz");

        descripcionCurso.setBackground(new java.awt.Color(21, 150, 135));
        descripcionCurso.setColumns(20);
        descripcionCurso.setForeground(new java.awt.Color(255, 255, 255));
        descripcionCurso.setLineWrap(true);
        descripcionCurso.setRows(10);
        descripcionCurso.setAutoscrolls(false);
        descripcionCurso.setBorder(null);
        descripcionCurso.setDragEnabled(false);
        descripcionCurso.setFocusTraversalKeysEnabled(false);
        descripcionCurso.setFocusable(false);
        descripcionCurso.setHighlighter(null);
        descripcionCurso.setRequestFocusEnabled(false);
        descripcionCurso.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(descripcionCurso);

        javax.swing.GroupLayout containerCursosLayout = new javax.swing.GroupLayout(containerCursos);
        containerCursos.setLayout(containerCursosLayout);
        containerCursosLayout.setHorizontalGroup(
            containerCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCursosLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(containerCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(actionBtn)
                    .addComponent(autor)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(containerCursosLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(imageCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        containerCursosLayout.setVerticalGroup(
            containerCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerCursosLayout.createSequentialGroup()
                .addGroup(containerCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerCursosLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(imageCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerCursosLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(nameCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(containerCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addGroup(containerCursosLayout.createSequentialGroup()
                        .addComponent(actionBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(autor)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel9.add(containerCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 1230, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:

        goTo("Home");
    }//GEN-LAST:event_HomeMouseClicked

    private void photoProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_photoProfileMouseClicked

    private void userNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameMouseClicked

    /**
     * opciones segun el estado del usuario y el curso
     *
     * @param evt
     */
    private void actionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionBtnMouseClicked
        // TODO add your handling code here:
        if (validateCourse) {//si no esta registrado

            try {
                Connection conDB = DB.getConection();

                String queryInsert = " INSERT INTO inscrito (id_curso, id_usuario)"
                        + " values (?, ?)";

                PreparedStatement ps = conDB.prepareStatement(queryInsert);

                ps.setString(1, id_course);
                ps.setString(2, String.valueOf(user.getId()));
                ps.execute();

                conDB.close();

                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Te haz inscrito a este curso", "Felicidades", JOptionPane.INFORMATION_MESSAGE);
                validateCourse = true;

                validateExist();

            } catch (SQLException ex) {
                System.err.println("Error sql cursoview: " + ex.getMessage());
            }

        } else {//si esta reistrado
            System.out.println("Click");

            int selectedIndex = listContentCourse.getSelectedIndex();

            if (selectedIndex != -1) {//validate index list 
                id_contenido = model.get(selectedIndex).getId();
                CursoD doo = new CursoD();

            }
        }


    }//GEN-LAST:event_actionBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    private javax.swing.JLabel actionBtn;
    private javax.swing.JLabel autor;
    private java.awt.Button button1;
    private javax.swing.JPanel containerCursos;
    private javax.swing.JTextArea descripcionCurso;
    private javax.swing.JLabel imageCourse;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JList listContentCourse;
    private java.awt.Label nameCourse;
    private javax.swing.JLabel photoProfile;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void goTo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void goTo(String screen) {

        switch (screen) {
            case "Home":
                this.dispose();
                Home h = new Home(user);
                h.setVisible(true);
                break;

            default:
                System.out.println("No se selecciono nada");
                break;
        }

    }

    @Override
    public void initViews() {
        model = new DefaultListModel<>();
        try {
            Connection conDB = DB.getConection();
            Statement state = conDB.createStatement();
            Statement state2 = conDB.createStatement();

            String consulta = "SELECT * FROM contenido WHERE id_curso = '" + id_course + "' ORDER BY id ASC";
            ResultSet resultset = state.executeQuery(consulta);

            if (resultset != null) {

                while (resultset.next()) {
                    // get fields
                    Integer id = resultset.getInt("id");
                    Integer id_course = resultset.getInt("id_curso");
                    String nombre = resultset.getString("nombre");
                    String url = resultset.getString("url");
                    String descripcion = resultset.getString("descripcion");
                    String created_at = resultset.getString("created_at");
                    String updated_at = resultset.getString("updated_at");

                    model.addElement(new Contenido(id, id_course, nombre, url, descripcion, created_at, updated_at));

                }

            }

            String con = "SELECT * FROM curso WHERE id = '" + id_course + "'";
            ResultSet rs = state2.executeQuery(con);

            if (rs != null) {
                rs.next();

                nameCourse.setText(rs.getString("nombre"));

                try {
                    Image image = null;
                    URL url = new URL("http://lunainc.com.mx/cursos/" + rs.getString("img"));
                    image = ImageIO.read(url);
                    imageCourse.setIcon(new ImageIcon(image));
                } catch (Exception e) {
                    System.err.println("Error al descargar la imagen: "+e.getMessage());

                }

                descripcionCurso.setText(rs.getString("descripcion"));

                autor.setText("Autor: " + rs.getString("autor"));

            }

        } catch (SQLException ex) {

            System.out.println("Error sql: " + ex.getMessage());

        }

        // create JList with model
        listContentCourse.setModel(model);
        // set cell renderer
        listContentCourse.setCellRenderer(new ContenidoRenderer());
        int selectedIndex = listContentCourse.getSelectedIndex();
        if (selectedIndex != -1) {
            id_contenido = model.get(selectedIndex).getId();
        }
    }

}
